name: Check YouTube Channels
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering
jobs:
  check-youtube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser
    - name: Load posted videos
      run: |
        if [ -f posted_videos.json ]; then
          echo "Posted videos file exists"
        else
          echo "{}" > posted_videos.json
          echo "Created empty posted videos file"
        fi
    - name: Run script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python main.py
    - name: Display log
      run: cat bot_log.txt
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add posted_videos.json bot_log.txt
        git commit -m "Update posted videos and log" || echo "No changes to commit"
        git push || echo "No changes to push"
